name: AutoLabs Attendance Check

on:
  schedule:
    # 한국 시간 기준 매일 밤 11:55에 실행 (UTC 14:55)
    - cron: '55 14 * * *'
  workflow_dispatch:  # 수동 실행 옵션 추가

jobs:
  attendance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Run attendance script
        run: python attendance.py
        env:
          AUTOLABS_USER_ID: ${{ secrets.AUTOLABS_USER_ID }}
          AUTOLABS_PASSWORD: ${{ secrets.AUTOLABS_PASSWORD }}
