name: AutoLabs Attendance Check

on:
  schedule:
    # 한국 시간 기준 매일 밤 12:00에 실행 (UTC 15:00)
    - cron: '00 15 * * *'
  workflow_dispatch:  # 수동 실행 옵션 추가

jobs:
  attendance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install axios

      - name: Run attendance script
        run: node attendance.js
        env:
          AUTOLABS_USER_ID: ${{ secrets.AUTOLABS_USER_ID }}
          AUTOLABS_PASSWORD: ${{ secrets.AUTOLABS_PASSWORD }}
